;; SatGuard Badge System
(define-constant admin tx-sender)
(define-data-var badge-count uint u0)
(define-map badges uint {name: (string-utf8 32), desc: (string-utf8 64)})
(define-map user-badges {user: principal, badge: uint} bool)
(define-read-only (get-badge (id uint)) (map-get? badges id))
(define-read-only (has-badge (user principal) (id uint)) (default-to false (map-get? user-badges {user: user, badge: id})))
(define-public (create-badge (name (string-utf8 32)) (desc (string-utf8 64)))
  (let ((id (var-get badge-count)))
    (asserts! (is-eq tx-sender admin) (err u401))
    (map-set badges id {name: name, desc: desc})
    (var-set badge-count (+ id u1)) (ok id)))
(define-public (award-badge (user principal) (id uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-set user-badges {user: user, badge: id} true) (ok true)))
