;; SatGuard Coverage Limits
(define-constant admin tx-sender)
(define-data-var global-max uint u100000000)
(define-data-var per-user-max uint u10000000)
(define-map user-coverage principal uint)
(define-read-only (get-global-max) (var-get global-max))
(define-read-only (get-user-max) (var-get per-user-max))
(define-read-only (get-user-coverage (user principal)) (default-to u0 (map-get? user-coverage user)))
(define-read-only (can-cover (user principal) (amt uint))
  (and (<= (+ (get-user-coverage user) amt) (var-get per-user-max)) (<= amt (var-get global-max))))
(define-public (record-coverage (user principal) (amt uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-set user-coverage user (+ (get-user-coverage user) amt)) (ok true)))
(define-public (set-limits (global uint) (per-user uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (var-set global-max global) (var-set per-user-max per-user) (ok true)))
