;; SatGuard Fee Engine
(define-constant admin tx-sender)
(define-data-var base-fee uint u100)
(define-data-var discount-threshold uint u5000000)
(define-data-var discount-pct uint u20)
(define-read-only (get-base-fee) (var-get base-fee))
(define-read-only (calc-fee (amount uint))
  (let ((fee (/ (* amount (var-get base-fee)) u10000)))
    (if (>= amount (var-get discount-threshold))
      (- fee (/ (* fee (var-get discount-pct)) u100)) fee)))
(define-public (set-base-fee (f uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401)) (var-set base-fee f) (ok true)))
(define-public (set-discount (thresh uint) (pct uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (var-set discount-threshold thresh) (var-set discount-pct pct) (ok true)))
