;; SatGuard Multisig
(define-constant admin tx-sender)
(define-data-var required-sigs uint u2)
(define-map signers principal bool)
(define-map tx-sigs {tx-id: uint, signer: principal} bool)
(define-map tx-sig-count uint uint)
(define-read-only (is-signer (user principal)) (default-to false (map-get? signers user)))
(define-read-only (get-sig-count (tx-id uint)) (default-to u0 (map-get? tx-sig-count tx-id)))
(define-read-only (is-approved (tx-id uint)) (>= (get-sig-count tx-id) (var-get required-sigs)))
(define-public (add-signer (user principal))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-set signers user true) (ok true)))
(define-public (sign-tx (tx-id uint))
  (begin (asserts! (is-signer tx-sender) (err u403))
    (asserts! (is-none (map-get? tx-sigs {tx-id: tx-id, signer: tx-sender})) (err u409))
    (map-set tx-sigs {tx-id: tx-id, signer: tx-sender} true)
    (map-set tx-sig-count tx-id (+ (get-sig-count tx-id) u1)) (ok true)))
