;; SatGuard Oracle Registry
(define-constant admin tx-sender)
(define-data-var oracle-count uint u0)
(define-map oracles uint {addr: principal, name: (string-utf8 32), active: bool})
(define-map oracle-trust principal uint)
(define-read-only (get-oracle (id uint)) (map-get? oracles id))
(define-read-only (get-trust (addr principal)) (default-to u0 (map-get? oracle-trust addr)))
(define-public (register-oracle (addr principal) (name (string-utf8 32)))
  (let ((id (var-get oracle-count)))
    (asserts! (is-eq tx-sender admin) (err u401))
    (map-set oracles id {addr: addr, name: name, active: true})
    (map-set oracle-trust addr u100)
    (var-set oracle-count (+ id u1)) (ok id)))
(define-public (set-trust (addr principal) (score uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-set oracle-trust addr score) (ok true)))
