;; SatGuard Policy Registry
(define-constant admin tx-sender)
(define-data-var policy-count uint u0)
(define-map policies uint {owner: principal, coverage: uint, premium: uint, expiry: uint, active: bool})
(define-read-only (get-policy (id uint)) (map-get? policies id))
(define-read-only (get-count) (var-get policy-count))
(define-public (create-policy (coverage uint) (premium uint) (duration uint))
  (let ((id (var-get policy-count)))
    (map-set policies id {owner: tx-sender, coverage: coverage, premium: premium, expiry: (+ block-height duration), active: true})
    (var-set policy-count (+ id u1)) (ok id)))
(define-public (cancel-policy (id uint))
  (let ((p (unwrap! (map-get? policies id) (err u404))))
    (asserts! (is-eq (get owner p) tx-sender) (err u403))
    (map-set policies id (merge p {active: false})) (ok true)))
