;; SatGuard Pool Boost
(define-constant admin tx-sender)
(define-map boosts uint {multiplier: uint, expires: uint})
(define-read-only (get-boost (pool-id uint)) (map-get? boosts pool-id))
(define-read-only (is-boosted (pool-id uint))
  (match (map-get? boosts pool-id)
    b (> (get expires b) block-height)
    false))
(define-read-only (get-multiplier (pool-id uint))
  (match (map-get? boosts pool-id)
    b (if (> (get expires b) block-height) (get multiplier b) u100)
    u100))
(define-public (set-boost (pool-id uint) (mult uint) (duration uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-set boosts pool-id {multiplier: mult, expires: (+ block-height duration)}) (ok true)))
(define-public (remove-boost (pool-id uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (map-delete boosts pool-id) (ok true)))
