;; SatGuard Rewards Pool
(define-constant admin tx-sender)
(define-data-var reward-pool uint u0)
(define-data-var reward-rate uint u5)
(define-map claimed principal uint)
(define-read-only (get-pool) (var-get reward-pool))
(define-read-only (get-rate) (var-get reward-rate))
(define-read-only (get-claimed (user principal)) (default-to u0 (map-get? claimed user)))
(define-public (fund-pool (amt uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (var-set reward-pool (+ (var-get reward-pool) amt)) (ok true)))
(define-public (claim-reward (amt uint))
  (begin (asserts! (<= amt (var-get reward-pool)) (err u402))
    (var-set reward-pool (- (var-get reward-pool) amt))
    (map-set claimed tx-sender (+ (get-claimed tx-sender) amt)) (ok true)))
(define-public (set-rate (r uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401)) (var-set reward-rate r) (ok true)))
