;; SatGuard Reserve Fund
(define-constant admin tx-sender)
(define-data-var reserve-balance uint u0)
(define-data-var min-reserve uint u500000)
(define-read-only (get-reserve) (var-get reserve-balance))
(define-read-only (get-min-reserve) (var-get min-reserve))
(define-read-only (is-healthy) (>= (var-get reserve-balance) (var-get min-reserve)))
(define-public (deposit (amt uint))
  (begin (var-set reserve-balance (+ (var-get reserve-balance) amt)) (ok true)))
(define-public (withdraw (amt uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401))
    (asserts! (>= (var-get reserve-balance) amt) (err u402))
    (var-set reserve-balance (- (var-get reserve-balance) amt)) (ok true)))
(define-public (set-min-reserve (m uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401)) (var-set min-reserve m) (ok true)))
