;; SatGuard Staking Rewards
(define-constant admin tx-sender)
(define-data-var reward-per-block uint u10)
(define-map last-claim principal uint)
(define-map staked-amount principal uint)
(define-read-only (get-reward-rate) (var-get reward-per-block))
(define-read-only (get-staked (user principal)) (default-to u0 (map-get? staked-amount user)))
(define-read-only (get-last-claim (user principal)) (default-to u0 (map-get? last-claim user)))
(define-read-only (pending-rewards (user principal))
  (let ((blocks (- block-height (get-last-claim user)))
        (stake (get-staked user)))
    (/ (* blocks (var-get reward-per-block) stake) u1000000)))
(define-public (stake (amt uint))
  (begin (map-set staked-amount tx-sender (+ (get-staked tx-sender) amt))
    (map-set last-claim tx-sender block-height) (ok true)))
(define-public (claim-rewards)
  (begin (map-set last-claim tx-sender block-height) (ok (pending-rewards tx-sender))))
(define-public (set-reward-rate (r uint))
  (begin (asserts! (is-eq tx-sender admin) (err u401)) (var-set reward-per-block r) (ok true)))
