;; SatGuard User Stats Tracker
(define-map user-stats principal {pools-joined: uint, claims-made: uint, contributions: uint, joined-at: uint})
(define-read-only (get-stats (user principal))
  (default-to {pools-joined: u0, claims-made: u0, contributions: u0, joined-at: u0} (map-get? user-stats user)))
(define-public (init-user)
  (begin (asserts! (is-none (map-get? user-stats tx-sender)) (err u409))
    (map-set user-stats tx-sender {pools-joined: u0, claims-made: u0, contributions: u0, joined-at: block-height}) (ok true)))
(define-public (inc-pools)
  (let ((s (get-stats tx-sender)))
    (map-set user-stats tx-sender (merge s {pools-joined: (+ (get pools-joined s) u1)})) (ok true)))
(define-public (inc-claims)
  (let ((s (get-stats tx-sender)))
    (map-set user-stats tx-sender (merge s {claims-made: (+ (get claims-made s) u1)})) (ok true)))
(define-public (inc-contributions)
  (let ((s (get-stats tx-sender)))
    (map-set user-stats tx-sender (merge s {contributions: (+ (get contributions s) u1)})) (ok true)))
